version: '3.8'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: pizzadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-boot-app:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pizzadb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  client-app:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - spring-boot-app

volumes:
  postgres_data:
